### PR TITLE
Set 'limit' to the tastypie default

### PR DESCRIPTION
**Pull request by alex-hutton**

### CODE REVIEW

**Comment by koterpillar** [comment]
Does it actually support pagination now? Can you add those parameters?

**Comment by alex-hutton** [comment]
No it doesn't support pagination... we may be able to write the tests in hsnet_admin without actually paginating... I still need to look at how I write the new tests for those features. This is just a fix needed because otherwise there is a divide by zero when hsnet_admin attempts to do (meta['offset'] / meta['limit']).

**Comment by koterpillar** [comment]
How can you write tests for the pagination functionality if you are not paginating?

**Comment by alex-hutton** [comment]
I can check that the paginator contains the correct hrefs in its links

**Comment by koterpillar** [comment]
The hrefs are not correct unless they take you anywhere.

**Comment by alex-hutton** [comment]
the params get passed through to profiles, so if the url is correct we can assume the data displayed on the list will be the correct data from profiles.

**Comment by koterpillar** [comment]
Okay, so this can go through because it's the default limit and it should be the same on the mock. However, I don't think checking the URLs is sufficient for the testing.

**Pull request merged**
